In [8]:
import os
import pandas as pd
import datetime
from datetime import datetime
import math
import numpy as np



df_whole = pd.DataFrame()
ride_file = "G:\\My Drive\\Cindy\\IB11\\Math IA\\ridedatanew\\rides.csv"
df_ride = pd.read_csv(ride_file, header=0)
meta_file = "G:\\My Drive\\Cindy\\IB11\\Math IA\\Metadata\\metadata.csv"
df_meta = pd.read_csv(meta_file, header=0)


Data Exopler

In [9]:
#df_explorer =  df_whole[(df_whole["Ride"] == "philharmagic") & (df_whole["Ride"] == "philharmagic")]
#df_explorer = df_explorer.groupby('NewTime',as_index = False).aggregate({'Waittime':'mean'})
#print(df_explorer.head(100))
#df_explorer.to_csv("c://temp//export.csv")

Display the result from source file

In [10]:
print(df_ride.tail(15))
print(df_meta.head(15))


         Unnamed: 0        date          datetime  SACTMIN  SPOSTMIN  \
2861011      298691  12/28/2021  2021-12-28 21:30      NaN      55.0   
2861012      298692  12/28/2021  2021-12-28 21:39      NaN      45.0   
2861013      298693  12/28/2021  2021-12-28 21:48      NaN      45.0   
2861014      298694  12/28/2021  2021-12-28 21:54      NaN      45.0   
2861015      298695  12/28/2021  2021-12-28 22:00      NaN      45.0   
2861016      298696  12/28/2021  2021-12-28 22:06      NaN      45.0   
2861017      298697  12/28/2021  2021-12-28 22:12      NaN      45.0   
2861018      298698  12/28/2021  2021-12-28 22:18      NaN      45.0   
2861019      298699  12/28/2021  2021-12-28 22:18      NaN      40.0   
2861020      298700  12/28/2021  2021-12-28 22:30      NaN      40.0   
2861021      298701  12/28/2021  2021-12-28 22:36      NaN      40.0   
2861022      298702  12/28/2021  2021-12-28 22:39      NaN      35.0   
2861023      298703  12/28/2021  2021-12-28 22:48      NaN      

In [11]:
df_whole = pd.merge(df_ride, df_meta, left_on='date', right_on='DATE', how='inner')
#df_meta.info()
print(df_whole["YEAR"].head(5))



0    2015
1    2015
2    2015
3    2015
4    2015
Name: YEAR, dtype: int64


Z Test

In [12]:
Sun_mean=df_whole.loc[df_whole['DAYOFWEEK']==1,'Waittime'].mean()
Thurs_mean=df_whole.loc[df_whole['DAYOFWEEK']==5,'Waittime'].mean()
Sun_std=df_whole.loc[df_whole['DAYOFWEEK']==1,'Waittime'].std()
Thurs_std=df_whole.loc[df_whole['DAYOFWEEK']==5,'Waittime'].std()
no_of_Sun=df_whole.loc[df_whole['DAYOFWEEK'] ==1,'Waittime'].count()
no_of_Thurs=df_whole.loc[df_whole['DAYOFWEEK'] ==5,'Waittime'].count()
print(Sun_mean, Thurs_mean)
print(Sun_std, Thurs_std)
print(no_of_Sun, no_of_Thurs)

30.78498955658843 29.574201150021317
27.062681081816304 26.282697425724614
363387 347124


In [13]:
import numpy
from scipy.stats import norm
def twoSampZ(X1, X2, mudiff, sd1, sd2, n1, n2):
    print((X1 - X2))
    pooledSE = numpy.sqrt(sd1**2/n1 + sd2**2/n2)
    print(pooledSE)
    z = ((X1 - X2) - mudiff)/pooledSE
    print(z)
    pval = 2*(1 - norm.cdf(abs(z)))
    print(pval)
    return round(z,30), pval
z,p= twoSampZ(Sun_mean,Thurs_mean,0,Sun_std,Thurs_std,no_of_Sun,no_of_Thurs)
print('z=', z, 'p=',p)

1.210788406567115
0.06328871071965077
19.13119089959866
0.0
z= 19.13119089959866 p= 0.0


In [14]:
a = norm.cdf(abs(10))
print (a)

1.0


In [15]:
First_mean=df_whole.loc[(df_whole['MONTHOFYEAR']==3) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].mean()

Month of year with ride "philharmagic"

In [16]:
First_mean=df_whole.loc[(df_whole['MONTHOFYEAR']==1) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].mean()
Second_mean=df_whole.loc[(df_whole['MONTHOFYEAR']==7) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].mean()
First_std=df_whole.loc[(df_whole['MONTHOFYEAR']==1) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].std()
Second_std=df_whole.loc[(df_whole['MONTHOFYEAR']==7) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].std()
no_of_First=df_whole.loc[(df_whole['MONTHOFYEAR']==1) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].count()
no_of_Second=df_whole.loc[(df_whole['MONTHOFYEAR']==7) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].count()
print(First_mean, Second_mean)
print(First_std, Second_std)
print(no_of_First, no_of_Second)

10.941305741232489 12.213418479974772
5.8505600875667465 6.333856152640777
21842 25368


In [17]:
import numpy
from scipy.stats import norm
def twoSampZ(X1, X2, mudiff, sd1, sd2, n1, n2):
    pooledSE = numpy.sqrt(sd1**2/n1 + sd2**2/n2)
    z = ((X1 - X2) - mudiff)/pooledSE
    pval = 2*(1 - norm.cdf(abs(z)))
    return round(z,3), pval
z,p= twoSampZ(First_mean,Second_mean,0,First_std,Second_std,no_of_First,no_of_Second)
print('z=', z, 'p=',p)

z= -22.671 p= 0.0


Loop Throuth Year 

In [48]:
i = 9
for j in range(i+1,13):
    First_mean=df_whole.loc[(df_whole['MONTHOFYEAR']==i) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].mean() 
    Second_mean=df_whole.loc[(df_whole['MONTHOFYEAR']==j) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].mean()
    First_std=df_whole.loc[(df_whole['MONTHOFYEAR']==i) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].std()
    Second_std=df_whole.loc[(df_whole['MONTHOFYEAR']==j) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].std()
    no_of_First=df_whole.loc[(df_whole['MONTHOFYEAR']==i) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].count()
    no_of_Second=df_whole.loc[(df_whole['MONTHOFYEAR']==j) & (df_whole['Ride'] == 'philharmagic'),'Waittime'].count()     
    z,p= twoSampZ(First_mean,Second_mean,0,First_std,Second_std,no_of_First,no_of_Second)
    print ("First Month:", str(i), ";" "Second Month", str(j))
    print('z=', z, 'p=',p)

First Month: 11 ;Second Month 12
z= -23.69 p= 0.0


Loop through dayofweek

In [58]:
i = 6
for j in range(i+1, 8):
    Firstday_mean=df_whole.loc[df_whole['DAYOFWEEK']==i,'Waittime'].mean()
    Secondday_mean=df_whole.loc[df_whole['DAYOFWEEK']==j,'Waittime'].mean()
    Firstday_std=df_whole.loc[df_whole['DAYOFWEEK']==i,'Waittime'].std()
    Secondday_std=df_whole.loc[df_whole['DAYOFWEEK']==j,'Waittime'].std()
    no_of_Firstday=df_whole.loc[df_whole['DAYOFWEEK'] ==i,'Waittime'].count()
    no_of_Secondday=df_whole.loc[df_whole['DAYOFWEEK'] ==j,'Waittime'].count()
    z,p= twoSampZ(Firstday_mean,Secondday_mean,0,Firstday_std,Secondday_std,no_of_Firstday,no_of_Secondday)
    print("First day:", str(i),":","Second day:", str(j))
    print('z=', z, 'p=',p)  

First day: 6 : Second day: 7
z= -57.423 p= 0.0


Pearson Correlation Coefficient

In [18]:
df_whole_waittime_agg = df_whole.groupby('MONTHOFYEAR',as_index = False).aggregate({'Waittime':'mean'})
df_MONTHOFYEAR = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= 3) & (df_whole_waittime_agg["MONTHOFYEAR"] >=1)].MONTHOFYEAR
df_waittime = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= 3) & (df_whole_waittime_agg["MONTHOFYEAR"] >=1)]["Waittime"]
pcc = np.corrcoef(df_MONTHOFYEAR, df_waittime)
print(pcc)

[[1.         0.98740863]
 [0.98740863 1.        ]]


In [19]:
df_whole_waittime_agg = df_whole.groupby('MONTHOFYEAR',as_index = False).aggregate({'Waittime':'mean'})
start_month = 1
end_month = 12
df_MONTHOFYEAR = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)].MONTHOFYEAR
df_waittime = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)]["Waittime"]
pcc = np.corrcoef(df_MONTHOFYEAR, df_waittime)
print(pcc)

[[ 1.         -0.42726249]
 [-0.42726249  1.        ]]


Loop throuth months

In [20]:
df_whole_waittime_agg = df_whole.groupby('MONTHOFYEAR',as_index = False).aggregate({'Waittime':'mean'})
start_month = 1
end_month = 12
print("Start Month: ", str(start_month))
print("End Month: ", str(end_month))
df_MONTHOFYEAR = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)].MONTHOFYEAR
df_waittime = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)]["Waittime"]
pcc = np.corrcoef(df_MONTHOFYEAR, df_waittime)
print(pcc)

start_month = 1
end_month = 3
print("Start Month: ", str(start_month))
print("End Month: ", str(end_month))
df_MONTHOFYEAR = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)].MONTHOFYEAR
df_waittime = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)]["Waittime"]
pcc = np.corrcoef(df_MONTHOFYEAR, df_waittime)
print(pcc)
start_month = 3
end_month = 5
print("Start Month: ", str(start_month))
print("End Month: ", str(end_month))
df_MONTHOFYEAR = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)].MONTHOFYEAR
df_waittime = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)]["Waittime"]
pcc = np.corrcoef(df_MONTHOFYEAR, df_waittime)
print(pcc)

start_month = 6
end_month = 9
print("Start Month: ", str(start_month))
print("End Month: ", str(end_month))
df_MONTHOFYEAR = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)].MONTHOFYEAR
df_waittime = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)]["Waittime"]
pcc = np.corrcoef(df_MONTHOFYEAR, df_waittime)
print(pcc)

start_month = 9
end_month = 12
print("Start Month: ", str(start_month))
print("End Month: ", str(end_month))
df_MONTHOFYEAR = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)].MONTHOFYEAR
df_waittime = df_whole_waittime_agg[(df_whole_waittime_agg["MONTHOFYEAR"] <= end_month) & (df_whole_waittime_agg["MONTHOFYEAR"] >=start_month)]["Waittime"]
pcc = np.corrcoef(df_MONTHOFYEAR, df_waittime)
print(pcc)



Start Month:  1
End Month:  12
[[ 1.         -0.42726249]
 [-0.42726249  1.        ]]
Start Month:  1
End Month:  3
[[1.         0.98740863]
 [0.98740863 1.        ]]
Start Month:  3
End Month:  5
[[ 1.         -0.98800673]
 [-0.98800673  1.        ]]
Start Month:  6
End Month:  9
[[ 1.        -0.9733824]
 [-0.9733824  1.       ]]
Start Month:  9
End Month:  12
[[1.         0.98190356]
 [0.98190356 1.        ]]


By DayofYear

In [21]:
display(df_whole.head(10))

Unnamed: 0        date          datetime  SACTMIN  SPOSTMIN        Ride  \
0           0  01/01/2015   2015-01-01 8:35      NaN      10.0  SmallWorld   
1           1  01/01/2015   2015-01-01 9:18      NaN      10.0  SmallWorld   
2           2  01/01/2015   2015-01-01 9:52      NaN      40.0  SmallWorld   
3           3  01/01/2015  2015-01-01 10:57      NaN      20.0  SmallWorld   
4           4  01/01/2015  2015-01-01 10:57     33.0       NaN  SmallWorld   
5           5  01/01/2015  2015-01-01 10:59      NaN      30.0  SmallWorld   
6           6  01/01/2015  2015-01-01 11:03      NaN      20.0  SmallWorld   
7           7  01/01/2015  2015-01-01 11:08      NaN      30.0  SmallWorld   
8           8  01/01/2015  2015-01-01 11:10      NaN      55.0  SmallWorld   
9           9  01/01/2015  2015-01-01 11:30      NaN      60.0  SmallWorld   

  oritime  Hour  Mins NewTime  ...  HSFIREWKS AKPRDDAY AKPRDDT1  AKPRDDT2  \
0   08:35     8    35   08:30  ...          1        0      NaN       NaN   
1   09:18     9    18   09:15  ...          1        0      NaN       NaN   
2   09:52     9    52   09:45  ...          1        0      NaN       NaN   
3   10:57    10    57   10:45  ...          1        0      NaN       NaN   
4   10:57    10    57   10:45  ...          1        0      NaN       NaN   
5   10:59    10    59   10:45  ...          1        0      NaN       NaN   
6   11:03    11     3   11:00  ...          1        0      NaN       NaN   
7   11:08    11     8   11:00  ...          1        0      NaN       NaN   
8   11:10    11    10   11:00  ...          1        0      NaN       NaN   
9   11:30    11    30   11:30  ...          1        0      NaN       NaN   

   AKPRDDN  AKFIREN  AKSHWNGT  AKSHWNT1 AKSHWNT2  AKSHWNN  
0      NaN      NaN         0       NaN      NaN      NaN  
1      NaN      NaN         0       NaN      NaN      NaN  
2      NaN      NaN         0       NaN      NaN      NaN  
3      NaN      NaN         0       NaN      NaN      NaN  
4      NaN      NaN         0       NaN      NaN      NaN  
5      NaN      NaN         0       NaN      NaN      NaN  
6      NaN      NaN         0       NaN      NaN      NaN  
7      NaN      NaN         0       NaN      NaN      NaN  
8      NaN      NaN         0       NaN      NaN      NaN  
9      NaN      NaN         0       NaN      NaN      NaN  

[10 rows x 192 columns]

Loop through day

In [31]:
df_whole_waittime_DAYOFWEEK_agg = df_whole.groupby('DAYOFWEEK',as_index = False).aggregate({'Waittime':'mean'})
start_day = 1
end_day = 7
print("Start Day: ", str(start_day))
print("End Day: ", str(end_day))
df_DAYOFWEEK = df_whole_waittime_DAYOFWEEK_agg[(df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] <= end_day) & (df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] >=start_day)].DAYOFWEEK
df_dayofyear_waittime = df_whole_waittime_DAYOFWEEK_agg[(df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] <= end_day) & (df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] >=start_day)]["Waittime"]
pcc = np.corrcoef(df_DAYOFWEEK, df_dayofyear_waittime)
print(pcc)

start_day = 1
end_day = 2
print("Start Day: ", str(start_day))
print("End Day: ", str(end_day))
df_DAYOFWEEK = df_whole_waittime_DAYOFWEEK_agg[(df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] <= end_day) & (df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] >=start_day)].DAYOFWEEK
df_dayofyear_waittime = df_whole_waittime_DAYOFWEEK_agg[(df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] <= end_day) & (df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] >=start_day)]["Waittime"]
pcc = np.corrcoef(df_DAYOFWEEK, df_dayofyear_waittime)
print(pcc)

start_day = 2
end_day = 5
print("Start Day: ", str(start_day))
print("End Day: ", str(end_day))
df_DAYOFWEEK = df_whole_waittime_DAYOFWEEK_agg[(df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] <= end_day) & (df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] >=start_day)].DAYOFWEEK
df_dayofyear_waittime = df_whole_waittime_DAYOFWEEK_agg[(df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] <= end_day) & (df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] >=start_day)]["Waittime"]
pcc = np.corrcoef(df_DAYOFWEEK, df_dayofyear_waittime)
print(pcc)

start_day = 5
end_day = 6
print("Start Day: ", str(start_day))
print("End Day: ", str(end_day))
df_DAYOFWEEK = df_whole_waittime_DAYOFWEEK_agg[(df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] <= end_day) & (df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] >=start_day)].DAYOFWEEK
df_dayofyear_waittime = df_whole_waittime_DAYOFWEEK_agg[(df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] <= end_day) & (df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] >=start_day)]["Waittime"]
pcc = np.corrcoef(df_DAYOFWEEK, df_dayofyear_waittime)
print(pcc)

start_day = 6
end_day = 7
print("Start Day: ", str(start_day))
print("End Day: ", str(end_day))
df_DAYOFWEEK = df_whole_waittime_DAYOFWEEK_agg[(df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] <= end_day) & (df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] >=start_day)].DAYOFWEEK
df_dayofyear_waittime = df_whole_waittime_DAYOFWEEK_agg[(df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] <= end_day) & (df_whole_waittime_DAYOFWEEK_agg["DAYOFWEEK"] >=start_day)]["Waittime"]
pcc = np.corrcoef(df_DAYOFWEEK, df_dayofyear_waittime)
print(pcc)

Start Day:  1
End Day:  7
[[ 1.         -0.11122968]
 [-0.11122968  1.        ]]
Start Day:  1
End Day:  2
[[1. 1.]
 [1. 1.]]
Start Day:  2
End Day:  5
[[ 1.         -0.92803836]
 [-0.92803836  1.        ]]
Start Day:  5
End Day:  6
[[1. 1.]
 [1. 1.]]
Start Day:  6
End Day:  7
[[1. 1.]
 [1. 1.]]


In [19]:
print(df_whole.columns)

Index(['Unnamed: 0', 'date', 'datetime', 'SACTMIN', 'SPOSTMIN', 'Ride',
       'oritime', 'Hour', 'Mins', 'NewTime',
       ...
       'HSFIREWKS', 'AKPRDDAY', 'AKPRDDT1', 'AKPRDDT2', 'AKPRDDN', 'AKFIREN',
       'AKSHWNGT', 'AKSHWNT1', 'AKSHWNT2', 'AKSHWNN'],
      dtype='object', length=192)


Aggregation

In [20]:
df_whole_time_agg = df_whole.groupby('NewTime',as_index = False).aggregate({'Waittime':'mean'})
df_whole_time_agg['numtime'] = df_whole_time_agg.apply(lambda x: x['NewTime'].replace(":","."), axis=1)
df_whole_time_agg['numtime']  = pd.to_numeric(df_whole_time_agg['numtime'])
print(df_whole_time_agg)

   NewTime   Waittime  numtime
0    00:00   9.697537     0.00
1    00:15   9.115983     0.15
2    00:30   8.633333     0.30
3    00:45   7.885906     0.45
4    01:00   8.201635     1.00
..     ...        ...      ...
91   22:45  11.811428    22.45
92   23:00  11.323538    23.00
93   23:15  11.303677    23.15
94   23:30  10.459746    23.30
95   23:45  10.112708    23.45

[96 rows x 3 columns]


whole day (9:00 to 23:00)

In [21]:
df_NewTime = df_whole_time_agg[(df_whole_time_agg["NewTime"] <= "23:00") & (df_whole_time_agg["NewTime"] >="09:00")].numtime
df_waittime = df_whole_time_agg[(df_whole_time_agg["NewTime"] <= "23:00") & (df_whole_time_agg["NewTime"] >="09:00")]["Waittime"]
pcc = np.corrcoef(df_NewTime, df_waittime)
print(pcc)

[[ 1.         -0.60292292]
 [-0.60292292  1.        ]]


morning (9:00 - 11:00)

In [22]:
df_NewTime = df_whole_time_agg[(df_whole_time_agg["NewTime"] <= "11:00") & (df_whole_time_agg["NewTime"] >="09:00")].numtime
df_waittime = df_whole_time_agg[(df_whole_time_agg["NewTime"] <= "11:00") & (df_whole_time_agg["NewTime"] >="09:00")]["Waittime"]
pcc = np.corrcoef(df_NewTime, df_waittime)
print(pcc)

[[1.         0.92947435]
 [0.92947435 1.        ]]


Afternoon (12:00 - 23:00)

In [23]:
df_NewTime = df_whole_time_agg[(df_whole_time_agg["NewTime"] <= "23:00") & (df_whole_time_agg["NewTime"] >="12:00")].numtime
df_waittime = df_whole_time_agg[(df_whole_time_agg["NewTime"] <= "23:00") & (df_whole_time_agg["NewTime"] >="12:00")]["Waittime"]
pcc = np.corrcoef(df_NewTime, df_waittime)
print(pcc)

[[ 1.         -0.92962152]
 [-0.92962152  1.        ]]


ANOVA Test

In [24]:
from scipy import stats
grps = pd.unique(df_whole.DAYOFWEEK.values)
print(grps)
d_data = {grp:df_whole['Waittime'][df_whole.DAYOFWEEK == grp] for grp in grps}
#Test with same value
#F, p = stats.f_oneway(d_data[1], d_data[1], d_data[1],d_data[1],d_data[1],d_data[1],d_data[1])
F, p = stats.f_oneway(d_data[1], d_data[2], d_data[3],d_data[4],d_data[5],d_data[6],d_data[7])
print('F ={},p={}'.format(F,p))

[5 6 7 1 2 3 4]
F =1400.5261813453326,p=0.0


Chi-Square Test

In [25]:
dataset_table=pd.crosstab(df_whole[(df_whole["MONTHOFYEAR"] <= 3) & (df_whole["MONTHOFYEAR"] >=1)]["MONTHOFYEAR"],df_whole[(df_whole["MONTHOFYEAR"] <= 3) & (df_whole["MONTHOFYEAR"] >=1)]["Waittime"])
dataset_table

Waittime     0.0    5.0    10.0   15.0   20.0   25.0   30.0   35.0   40.0   \
MONTHOFYEAR                                                                  
1              130  23030  39710  19806  18283  12528  13833   9910  10846   
2               40  19257  34578  17219  15269  12045  13091  10013  10877   
3              118  16890  33265  18548  15660  12889  13018  10521  10662   

Waittime     45.0   ...  195.0  200.0  205.0  210.0  215.0  220.0  225.0  \
MONTHOFYEAR         ...                                                    
1             9137  ...     16     12      7     14     10      1      0   
2             9290  ...     16     21      5     33      3      0      1   
3            10798  ...     30     23      5      3      2      0      1   

Waittime     230.0  240.0  250.0  
MONTHOFYEAR                       
1                5     10      1  
2                4      0      0  
3                0      1      0  

[3 rows x 49 columns]